"""Remove username from User model

Revision ID: a87f3c6edab1
Revises: dfdd6306c31d
Create Date: 2024-07-30 22:27:55.123439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87f3c6edab1'
down_revision = 'dfdd6306c31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
