"""Add active field to Exam model

Revision ID: d25f138406e3
Revises: a87f3c6edab1
Create Date: 2024-07-31 02:00:07.090929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25f138406e3'
down_revision = 'a87f3c6edab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
